- name: app installation (Debian)
  tags:
    - debian
    - monero
    - packages
    - secure
  apt:
    name: monero
    state: present
  become: true
  when: ansible_distribution in ['Debian', 'Ubuntu']
