- name: installation (Debian)
  tags:
    - debian
    - torbrowser
    - packages
    - secure
  apt:
    name: torbrowser-launcher
    state: absent
  become: true
  when: ansible_distribution in ['Debian', 'Ubuntu']
