- name: installation (Debian)
  tags:
    - debian
    - torbrowser
    - packages
    - secure
  apt:
    name: torbrowser-launcher
    state: present
  become: true
  when:
    - ansible_distribution in ['Debian', 'Ubuntu']
    - ansible_architecture == "x86_64"
