---
- hosts: localhost
  connection: local
  vars_files:
    - vars/{{ ansible_distribution }}.yml
  pre_tasks:

    - name: install updates (Debian)
      tags: updates
      apt:
        upgrade: dist
        update_cache: yes
      become: true
      when: ansible_distribution in ['Debian', 'Ubuntu']

    - name: install updates (Darwin)
      tags: updates
      homebrew:
        update_homebrew: yes
        upgrade_all: yes
      become: false
      when: ansible_distribution == 'MacOSX'

    - name: remove init.sh script
      tags: always
      file:
        path: '{{ home_directory }}/init.sh'
        state: absent

- hosts: localhost
  vars_files:
    - vars/{{ ansible_distribution }}.yml
  roles:
    - core
    - dotfiles
    - repos
    - nodejs
    - neovim
    - github-cli
    - godot
    - brave
    - customisation
