- name: create required directories
  tags: dotfiles
  file:
    path: '{{ home_directory }}/{{ item }}'
    state: directory
    owner: '{{ owner }}'
    group: '{{ group }}'
    mode: 0755
  loop:
    - .config/git
    - .config/lazygit
    - .config/newsboat
    - .config/nvim
    - .config/nvim/lua
    - .config/nvim/lua/plugins
    - .local/share/applications
    - 1-projects
    - 2-areas
    - 3-resources
    - 3-resources/customisation
    - 3-resources/customisation/devdocs
    - 3-resources/customisation/fonts
    - 3-resources/customisation/macos-terminal-themes
    - 3-resources/notes
    - 3-resources/notes/scratchpads
    - 4-archive
    - bin

- name: sync dotfiles
  tags: dotfiles
  copy:
    src: '{{ item.package }}/{{ item.path }}'
    dest: '{{ home_directory }}/{{ item.path }}'
    owner: '{{ owner }}'
    group: '{{ group }}'
  loop:
    - { package: 'bash', path: '.bash_profile' }
    - { package: 'bash', path: '.bashrc' }
    - { package: 'bash', path: '.inputrc' }
    - { package: 'devdocs', path: '3-resources/customisation/devdocs/devdocs.json' }
    - { package: 'gcs', path: '.customize_environment' }
    - { package: 'git', path: '.config/git/git-commit-template.txt' }
    # - { package: 'git', path: '.gitconfig' }
    - { package: 'lazygit', path: '.config/lazygit/config.yml' }
    - { package: 'newsboat', path: '.config/newsboat/config' }
    - { package: 'newsboat', path: '.config/newsboat/urls' }
    - { package: 'nvim', path: '.config/nvim/init.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/lsp.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/binds.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/options.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/plugins.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/plugins/formatter-config.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/plugins/nvim-cmp-config.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/plugins/telescope-config.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/plugins/treesitter-config.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/plugins/which-key-config.lua' }
    - { package: 'scripts', path: 'bin/scratch.sh' }
    - { package: 'shell', path: '.shell_aliases' }
    - { package: 'shell', path: '.shell_common' }
    - { package: 'themes', path: '3-resources/customisation/macos-terminal-themes/zenburn.terminal' }
    - { package: 'tmux', path: '.tmux.conf' }
    - { package: 'zsh', path: '.zshrc' }

- name: making scripts executable
  tags: dotfiles
  file:
    dest: '{{ home_directory }}/bin/{{ item }}'
    mode: a+x
  loop:
    - scratch.sh
