- name: pull down dotfiles repository
  tags:
    - dotfiles
    - repos
  git:
    repo: git@github.com:brotherkaif/dotfiles.git
    dest: '{{ home_directory }}/dotfiles'

- name: run bootstrap script
  tags:
    - dotfiles
    - scripts
  script:
    cmd: '{{ home_directory }}/dotfiles/bootstrap.sh'
