- name: pull down dotfiles repository
  tags: dotfiles
  git:
    repo: git@github.com:brotherkaif/dotfiles.git
    dest: '{{ home_directory }}/dotfiles'

- name: run symlink_dotfiles script
  tags: dotfiles
  script:
    cmd: '{{ home_directory }}/dotfiles/scripts/symlink_dotfiles.sh'
