- name: create required directories
  tags: dotfiles
  file:
    path: '{{ home_directory }}/{{ item }}'
    state: directory
    owner: '{{ owner }}'
    group: '{{ group }}'
    mode: 0755
  loop:
    - projects
    - areas
    - resources
    - archive
    - .local/share/applications
    - .config/git
    - .config/nvim
    - .config/nvim/lua
    - .config/nvim/lua/plugins
    - .local/share/amfora
    - .config/amfora

- name: sync dotfiles
  tags: dotfiles
  copy:
    src: '{{ item.package }}/{{ item.path }}'
    dest: '{{ home_directory }}/{{ item.path }}'
    owner: '{{ owner }}'
    group: '{{ group }}'
  loop:
    - { package: 'bash', path: '.bashrc' }
    - { package: 'bash', path: '.bash_profile' }
    - { package: 'bash', path: '.inputrc' }
    - { package: 'zsh', path: '.zshrc' }
    - { package: 'tmux', path: '.tmux.conf' }
    - { package: 'git', path: '.gitconfig' }
    - { package: 'git', path: '.config/git/git-commit-template.txt' }
    - { package: 'gcs', path: '.customize_environment' }
    - { package: 'nvim', path: '.config/nvim/init.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/binds.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/options.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/plugins.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/lsp.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/plugins/treesitter-config.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/plugins/compe-config.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/plugins/formatter-config.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/plugins/telescope-config.lua' }
    - { package: 'amfora', path: '.local/share/amfora/bookmarks.toml' }
    - { package: 'amfora', path: '.local/share/amfora/subscriptions.json' }
    - { package: 'amfora', path: '.config/amfora/config.toml' }
