- name: create required directories
  tags: dotfiles
  file:
    path: '{{ home_directory }}/{{ item }}'
    state: directory
    owner: '{{ owner }}'
    group: '{{ group }}'
    mode: 0755
  loop:
    - 1-projects
    - 2-areas
    - 3-resources
    - 3-resources/customisation
    - 3-resources/customisation/devdocs
    - 3-resources/customisation/macos-terminal-themes
    - 3-resources/customisation/fira-code-font
    - 4-archive
    - .local/share/applications
    - .config/git
    - .config/nvim
    - .config/nvim/lua
    - .config/nvim/lua/plugins
    - .local/share/amfora
    - .config/amfora

- name: sync dotfiles
  tags: dotfiles
  copy:
    src: '{{ item.package }}/{{ item.path }}'
    dest: '{{ home_directory }}/{{ item.path }}'
    owner: '{{ owner }}'
    group: '{{ group }}'
  loop:
    - { package: 'bash', path: '.bashrc' }
    - { package: 'bash', path: '.bash_profile' }
    - { package: 'bash', path: '.inputrc' }
    - { package: 'zsh', path: '.zshrc' }
    - { package: 'tmux', path: '.tmux.conf' }
    - { package: 'git', path: '.gitconfig' }
    - { package: 'git', path: '.config/git/git-commit-template.txt' }
    - { package: 'gcs', path: '.customize_environment' }
    - { package: 'nvim', path: '.config/nvim/init.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/binds.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/options.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/plugins.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/lsp.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/plugins/treesitter-config.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/plugins/nvim-cmp-config.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/plugins/formatter-config.lua' }
    - { package: 'nvim', path: '.config/nvim/lua/plugins/telescope-config.lua' }
    - { package: 'amfora', path: '.local/share/amfora/bookmarks.toml' }
    - { package: 'amfora', path: '.local/share/amfora/subscriptions.json' }
    - { package: 'amfora', path: '.config/amfora/config.toml' }
    - { package: 'devdocs', path: '3-resources/customisation/devdocs/devdocs.json' }

- name: download Terminal.app themes
  tags:
    - dotfiles
    - customisation
  get_url:
    url: 'https://github.com/dracula/terminal-app/archive/master.zip'
    dest: ~/3-resources/customisation/macos-terminal-themes/
    mode: 0755

- name: download Fira Code font
  tags:
    - dotfiles
    - customisation
  get_url:
    url: 'https://github.com/tonsky/FiraCode/releases/download/5.2/Fira_Code_v5.2.zip'
    dest: ~/3-resources/customisation/fira-code-font/
    mode: 0755
