- name: installation (Debian)
  tags:
    - debian
    - glow
    - packages
  block:
    - name: download and unarchive (Debian)
      block:
        - name: x86_64 installation (Debian)
          apt:
            deb: https://github.com/charmbracelet/glow/releases/download/v1.4.1/glow_1.4.1_linux_amd64.deb
          when: ansible_architecture == "x86_64"

        - name: arm64 installation (Debian)
          apt:
            deb: https://github.com/charmbracelet/glow/releases/download/v1.4.1/glow_1.4.1_linux_arm64.deb
          when: ansible_architecture == "aarch64"
  become: true
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: installation (Darwin)
  tags:
    - darwin
    - glow
    - packages
  block:
    - name: package installation (Darwin)
      homebrew:
        name: glow
        state: present
  when: ansible_distribution == 'MacOSX'
