- name: base package installation (All)
  tags:
    - core
    - packages
  package:
    name:
      - stow
      - ripgrep
      - tmux
      - tree
      - htop
      - ncdu
      - git
      - pass
      - feh
      - mpv
      - ffmpeg
      - lynx
      - newsboat
      - figlet
      - toilet
    state: present
  become: '{{ should_be_root }}'

- name: additional package installation (Debian)
  tags:
    - debian
    - core
    - packages
  apt:
    name:
      - apt-transport-https
      - build-essential
      - python3-pip
    state: present
  become: true
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: additional package installation (Darwin)
  tags:
    - darwin
    - core
    - packages
  homebrew:
    name:
      - python
  when: ansible_distribution == 'MacOSX'
