- name: install base packages
  tags:
    - core
    - packages
  package:
    name:
      - ripgrep
      - tmux
      - tree
      - htop
      - git
      - pass
      - ffmpeg
      - figlet
      - toilet
    state: present
  become: '{{ should_be_root }}'

- name: additional mac packages
  tags:
    - core
    - packages
  homebrew:
    name:
      - python
  when: ansible_distribution == 'MacOSX'

- name: additional linux packages
  tags:
    - core
    - packages
  package:
    name:
      - build-essential
      - python3-pip
    state: present
  become: true
  when: ansible_distribution in ['Debian', 'Ubuntu']
