- name: base package installation (All)
  tags:
    - core
    - packages
  package:
    name:
      - git
      - stow
      - ripgrep
      - fzf
      - tmux
      - tree
      - htop
      - ncdu
      - feh
      - mpv
      - ffmpeg
      - lynx
      - newsboat
      - figlet
      - toilet
    state: present
  become: '{{ should_be_root }}'

- name: extend repositories (Debian)
  tags:
    - debian
    - core
    - packages
  apt_repository:
    repo: deb http://deb.debian.org/debian bullseye main contrib non-free
    state: present
  become: true
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: additional package installation (Debian)
  tags:
    - debian
    - core
    - packages
    - flatpak
  apt:
    name:
      - apt-transport-https
      - build-essential
      - python3-pip
      - flatpak
    state: present
  become: true
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: additional configuration (Debian)
  tags:
    - debian
    - core
    - config
    - flatpak
  block:
    - name: add the flathub flatpak repository remote to the user installation (Debian)
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user
      become: false
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: additional package installation (Darwin)
  tags:
    - darwin
    - core
    - packages
  homebrew:
    name:
      - python
  when: ansible_distribution == 'MacOSX'
