- name: base package installation (All)
  tags:
    - core
    - packages
  package:
    name:
      - ripgrep
      - tmux
      - tree
      - htop
      - git
      - pass
      - ffmpeg
      - figlet
      - toilet
    state: present
  become: '{{ should_be_root }}'

- name: additional package installation (Darwin)
  tags:
    - core
    - packages
  homebrew:
    name:
      - python
  when: ansible_distribution == 'MacOSX'

- name: additional package installation (Debian)
  tags:
    - core
    - packages
  block:
    - name: add the apt repository (Debian)
      apt_repository:
        repo: deb http://deb.debian.org/debian buster-backports main contrib non-free
        state: present

    - name: package installation (Debian)
      apt:
        name:
          - apt-transport-https
          - build-essential
          - python3-pip
          - torbrowser-launcher
        state: present
  become: true
  when: ansible_distribution in ['Debian', 'Ubuntu']
