"do not touch" = true

[bookmarks]
  m5sw22lone5c6l3bnzvhk3tffzwg63bp = "Anjune"
  m5sw22lone5c6l3gojuwk3ten4xg233oon2gk4rp = "uoou"
  "m5sw22lone5c6l3hmvws4y3iojuxg53fojss45llf4======" = "Chris Ware"
  "m5sw22lone5c6l3imv4gi43mfzrw6ltvnmxq====" = "HexDSL"
