- name: app installation (Debian)
  tags:
  - neovim
  - dev
  get_url:
    url: 'https://github.com/neovim/neovim/releases/download/v0.6.0/nvim.appimage'
    dest: /usr/bin/nvim
    mode: 0755
  become: true
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: app installation (Darwin)
  tags:
  - neovim
  - dev
  homebrew:
    name: neovim
    # state: head
  when: ansible_distribution == 'MacOSX'

- name: packer installation
  tags:
  - neovim
  - dev
  git:
    repo: https://github.com/wbthomason/packer.nvim.git
    dest: '{{ home_directory }}/.local/share/nvim/site/pack/packer/start/packer.nvim'

- name: lsp dependency installation
  tags:
  - neovim
  - dev
  npm:
    name: '{{ item }}'
    global: yes
  become: '{{ should_be_root }}'
  loop:
    # Ansible
    - ansible-language-server
    # Bash
    - bash-language-server
    # HTML/CSS/JSON
    - vscode-langservers-extracted
    # JavaScript/TypeScript
    - typescript
    - typescript-language-server
    - diagnostic-languageserver
    - eslint_d
    - prettier
    # YAML
    - yaml-language-server

- name: python dependency installation
  tags:
  - neovim
  - dev
  pip:
    name: pynvim
    extra_args: --user --upgrade
    executable: pip3
