- name: app installation (Debian)
  tags:
  - neovim
  - dev
  get_url:
    url: 'https://github.com/neovim/neovim/releases/download/v0.6.1/nvim.appimage'
    dest: /usr/bin/nvim
    mode: 0755
  become: true
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: app installation (Darwin)
  tags:
  - neovim
  - dev
  homebrew:
    name: neovim
    # state: head
  when: ansible_distribution == 'MacOSX'

- name: python dependency installation
  tags:
  - neovim
  - dev
  pip:
    name: pynvim
    extra_args: --user --upgrade
    executable: pip3
